### ISSUE TITLE
A dumbed down version of readme?

### ISSUE THREAD

**Issue by alystair** [cris691/beamsplitter#5]
I came across this randomly whilst looking into hash algos but know nothing of the math or research behind them. The readme is a bit confusing... perhaps you could add:

- what are the ideal uses cases, where would it be used?
- where shouldn't it be used?
- what this hash model means, how does it compare to something like MD5?
- it could be used as UUID?

It could help with adoption...

**Comment by cris691** [comment]
I'm okay if it's not publicly adopted. I'm not trying to get external validation for this, because I just made it because I wanted to and I know there are some cool people and orgs who appreciate it alot. I'm not trying to get lots of attention. It already has gotten some very important attention.

That being said, I'm okay to cover some basics:

It's fine as a non crypto hash because it works statistically, per the SMHasher results. but there's a lot of other very fast such hashes, optimized for speed. this it not. 

Also it can work in an adversarial situation where you have someone trying to abuse the hash hash because it's a universal hash. Again no there's a lot of Fast universal hashes out there.

I'm terms of publicly saying it's a good crypto hash, the way that works is people need to understand attacks on it. for the reasons I'm paragraph 1 I'm not interested in doing a write up like that but you've given me an idea.

I'm okay if the readme becomes like a crowdsourced record of attacks against this hash function. 

if you're interested in analyzing it further yourself I suggest you take a look at the source code because the main mixing functions are really very simple. If you'd like to see some sort of collection of the attack reports against it encouraged you to invite people to do that.

as I said I'm not interested in spearheading any such effort. I'm grateful to get your issue. And I appreciate your star!
